
name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Create env.properties file
      run: |
        mkdir -p src/main/resources/env.properties
        echo "DB_URL=${{ secrets.DB_URL }}" >> env.properties
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> env.properties
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> env.properties
        echo "JWT_CODE=${{ secrets.JWT_CODE }}" >> env.properties
        echo "NAVER_CLIENTID=${{ secrets.NAVER_CLIENTID }}" >> env.properties
        echo "NAVER_SERCRET=${{ secrets.NAVER_SERCRET }}" >> env.properties
        echo "KAKAO_CLIENTID=${{ secrets.KAKAO_CLIENTID }}" >> env.properties
        echo "KAKAO_SECRET=${{ secrets.KAKAO_SECRET }}" >> env.properties
        echo "GOOGLE_CLIENTID=${{ secrets.GOOGLE_CLIENTID }}" >> env.properties
        echo "GOOGLE_SERCRET=${{ secrets.GOOGLE_SERCRET }}" >> env.properties


    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
